
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package org.tensorflow.shapechecker;

/** CUP generated class containing symbol constants. */
public class Syms {
  /* terminals */
  public static final int COMMA = 3;
  public static final int NUMBER = 4;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int SCALAR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "COMMA",
  "NUMBER",
  "SCALAR"
  };
}

